export { default as CallCallAddTwotone } from './CallAdd';
export { default as CallCallCallingTwotone } from './CallCalling';
export { default as CallCallIncomingTwotone } from './CallIncoming';
export { default as CallCallMinusTwotone } from './CallMinus';
export { default as CallCallOutgoingTwotone } from './CallOutgoing';
export { default as CallCallReceivedTwotone } from './CallReceived';
export { default as CallCallRemoveTwotone } from './CallRemove';
export { default as CallCallSlashTwotone } from './CallSlash';
export { default as CallCallTwotone } from './Call';
