export { default as CallCallAddLinear } from './CallAdd';
export { default as CallCallCallingLinear } from './CallCalling';
export { default as CallCallIncomingLinear } from './CallIncoming';
export { default as CallCallMinusLinear } from './CallMinus';
export { default as CallCallOutgoingLinear } from './CallOutgoing';
export { default as CallCallReceivedLinear } from './CallReceived';
export { default as CallCallRemoveLinear } from './CallRemove';
export { default as CallCallSlashLinear } from './CallSlash';
export { default as CallCallLinear } from './Call';
